import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import { SideBar } from "@/components/SideBar";

const inter = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TH MOVIES",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} bg-[#1A161F] w-full h-full flex text-white`}>
        <SideBar/>
        {children}
      </body>
    </html>
  );
}
